var Transformer = {};

Transformer.transformResponse = function(responseCode, responseText, payload){
    if(!payload)
    {
        payload = {};
    }

    return {
        responseCode: responseCode,
        responseText: responseText,
        payload: payload
    };
};

Transformer.transformMember = function(MemberObject){
    return {
        id: MemberObject._id
    };
};

Transformer.transformAdmin = function(AdminObject){
    return {

    };
};

/**
 *
 * @param errors {Array}
 * @returns {string}
 * @description transforms errors generated by express validator to a single message string with each message separated by '|'
 */
Transformer.transformExpressValidationErrors = function(errors){
    var msgs = '';

    if(!Array.isArray(errors))
        return msgs;

    errors.forEach(function(item){
        msgs += (item.msg || '') + '|';
    });

    return msgs;
};

module.exports = Transformer;
